#!/bin/sh

LOCAL_IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)

export MYSQL_HOST_IP=$LOCAL_IP
export MYSQL_USER="dev"
export MYSQL_PASSWORD=""
export MYSQL_PORT="3306"
export MYSQL_DATABASE="rainmanland"
export NODE_ENV="production"

exec docker-compose $@

