version: '3.8'

x-common-variables: &common-variables
  MYSQL_DATABASE: $MYSQL_DATABASE
  MYSQL_USER: $MYSQL_USER 
  MYSQL_PASSWORD: ""
  MYSQL_HOST_IP: $MYSQL_HOST_IP
  NODE_ENV: $NODE_ENV

services:

  nginx:
    depends_on:
      - api
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"

  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    depends_on:
    volumes:
      - /app/node_modules
      - ./api:/app
    environment:
      <<: *common-variables
