#!/bin/bash

function error_handler() {
  echo "Error occurred in script at line: $1. Message: $2"
  exit 1
}

trap 'error_handler ${LINENO} "$?"' ERR
set -e

# 1. Pull the latest changes from the remote prod branch on GitHub
echo "Pulling the latest changes from the remote prod branch on GitHub..."
CURRENT_BRANCH=$(git symbolic-ref --short -q HEAD)
if [[ $CURRENT_BRANCH != "prod" ]]; then
  git checkout prod
fi
sudo git fetch origin prod & wait
sudo git reset --hard origin/prod & wait

# 2. Fetch the EC2 instance's local IP address using the AWS Metadata Service and store it in a variable
echo "Fetching the EC2 instance's local IP address..."
LOCAL_IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)

# 3. Edit the "pm2.json" file to convert the string "<EC2_HOST_IP_OR_HOSTNAME>" to the IP address string stored in the local IP variable
echo "Updating the pm2.json file with the local IP address..."
sudo sed -i "s|<EC2_HOST_IP_OR_HOSTNAME>|${LOCAL_IP}|g" pm2.json & wait

# 4. Run "docker-compose down" to ensure any unused containers are removed
echo "Removing unused containers..."
sudo docker-compose down & wait

# 5. Run "docker-compose up --build -d" to build and start the containers in detached mode
echo "Building and starting containers in detached mode..."
sudo docker-compose up --build -d & wait

exit 0

