FROM keymetrics/pm2:8-slim

# Bundle APP files
WORKDIR /app
COPY index.js .
COPY package.json .
COPY package-lock.json .
COPY pm2.json .
COPY dbController.js .

# Install app dependencies
ENV NPM_CONFIG_LOGLEVEL warn
RUN npm install --production
RUN apt-get update && apt-get install -y openssh-client && rm -rf /var/lib/apt/lists/*

# Get the entrypoint script and start the container
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

